/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110511-g55ea1da1c0-20230507"
#endif /* AVUTIL_FFVERSION_H */
